### ISSUE TITLE
Bundle exec and Docker entry point?

### ISSUE THREAD

**Issue by larryfox** [github/hoosegow#10]
This probably has more to do with conflicting environments than an actual bug, but I had to change the [Dockerfile `ENTRYPOINT`](https://github.com/github/hoosegow/blob/179abbc91a45efe57616c0ffa28330d097ebf3d4/Dockerfile#L46) to:

~~~
ENTRYPOINT /bin/bash -l -c 'bundle exec bin/hoosegow'
~~~

To avoid a `LoadError` when trying to run the image.

1. I'm guessing some combination of OS/Docker/Ruby differences are to blame. Is there a recommended stack for running hoosegow? (I'm on OS X 10.11.3, Docker 1.9.1 via Docker Toolbox, and Ruby 2.2.2 FWIW)

1. If this is a bug, I can send a PR but have no idea how I'd write a test for such a change. 🙃

**Comment by spraints** [comment]
> This probably has more to do with conflicting environments than an actual bug

Naw, this is probably an actual bug. The projects I've used hoosegow on have needed custom dependencies in the container, so we've used custom dockerfiles, too. I'd love a PR, and you don't need to test this.
